#!/usr/bin/env python

""" Script to generate a list of mailing lists with no digest members
"""

from MailmanLists import all_lists

if __name__ == '__main__':

    useless_digests = []
    
    for list in all_lists():
        if list.digestable != 0 and (len(list.getDigestMemberKeys())) == 0:
            useless_digests.append(list.real_name)

    print "There are %d lists with no digest members:" % \
        len(useless_digests)

    useless_digests.sort()

    for list in useless_digests:
        print list

