#!/bin/bash
#
# RPM Build Release Script
#
# (C) 2004 Naked Ape Consulting
# Wil Cooley <wcooley@nakedape.cc>

prog=$(basename $0)

pprintf () {
    printf "%s: " ${prog}
    printf "$@"
}

if [ $# -ne 1 ]; then
    printf "Usage: %s <specfile>\n" ${prog}
    exit 1
else
    specfile=$1
fi

if [ ! -f ${specfile} ]; then
    pprintf "${specfile} does not exist or is not a file!\n"
    exit 1
fi

# If you query a spec file that makes multiple packages, you get several
# values back.  Do a little array fiddling to get the first one
rpmbase=($(rpm -q --queryformat '%{NAME}\n' --specfile ${specfile}))[0]
rpmverrel=$(rpm -q --queryformat '%{VERSION}-%{RELEASE}\n' --specfile ${specfile})
tmpfile=$(mktemp /tmp/${prog}-${rpmbase}.XXXXXX) || exit 1

rpmreldir=$HOME/rpm/release/rpm/${rpmbase}
srpmreldir=$HOME/rpm/release/srpm/${rpmbase}

mkdir -p ${rpmreldir} ${srpmreldir}

pprintf "Output going to %s...\n" ${tmpfile}
pprintf "Building from %s now...\n" ${specfile}

(time rpmbuild -ba ${specfile} 2>&1) |tee ${tmpfile}

echo -en '\a'

if [ $? -ne 0 ]; then
    pprintf "Build exited with error status.\n\tPlease check %s.\n" ${tmpfile}
    exit 1
fi

srpm=$(awk '/^Wrote:.*src.rpm$/ {print $2}' ${tmpfile})
rpms=$(awk '/^Wrote:.*(noarch|i?86|athlon)/ {print $2}' ${tmpfile})

if [ $(echo $srpm|wc -c) -lt 5 ]; then
    printf "Error in build.  Inspect build log at ${tmpfile}.\n"
    exit 1
fi

pprintf "Signing packages...\n"
echo ${srpm} ${rpms} |xargs rpm --addsign

if [[ $? -gt 0 ]]; then
    printf "Package signing failed! Perhaps you mis-typed the passphrase?\nLet's try once more.\n"
    echo ${srpm} ${rpms} |xargs rpm --addsign

    if [[ $? -gt 0 ]]; then
        printf "Hm, sorry, package signing failed.  Aborting.\n"
        exit 1
    fi
fi

mv -iv "${rpms}" "${rpmreldir}"
mv -iv "${tmpfile}" "${rpmreldir}/buildlog-${rpmbase}-${rpmverrel}.log"
chmod 0444 "${rpmreldir}/buildlog-${rpmbase}-${rpmverrel}.log"
cp -av "${specfile}" "${rpmreldir}"
mv -iv "${srpm}" "${srpmreldir}"

for rpm in ${rpms}; do
    echo " RPM: " ${rpmreldir}/$(basename $rpm)
done

echo "SRPM: " ${srpmreldir}/$(basename $srpm)


# clean up
#rm -vf ${tmpfile}
