#!/bin/bash
# !!! MANAGED BY CFENGINE - EDIT ONLY THROUGH SVN !!!
#
# Written by Wil Cooley  <wcooley@nakedape.cc>
#
# services - Wrapper around /sbin/service and /sbin/chkconfig in Red Hat
# systems to allow multiple services to be controlled in one go or multiple
# service-related commands.
#

prog=$(basename $0)
ver=1.0
author="Wil Cooley <wcooley@nakedape.cc>"
copyright=$'Copyright (C) 2005 Naked Ape Consulting, Ltd.
Copyright (C) 2005 Wil Cooley
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
'

version() {
    printf "%s, version %s\n" "${prog}" "${ver}"
    printf "Written by %s\n" "${author}"
    echo -e "${copyright}"
}
usage() {
    cat <<EOF 
Usage: ${prog} <command> [service]...

${prog} is a wrapper around /sbin/service to multiple services to be controlled
with one command (I got tired of writing shell-loops).

<command> is one of:
    * start
    * stop
    * restart
    * condrestart
    * status
    * init-start    - Start services and enable on boot
    * init-stop     - Stop services and disable on boot
    * init-on       - Enable services on boot
    * init-off      - Disable services on boot

EOF
    version
}

if [ $# -lt 2 ]; then
    if [ $# -eq 1 ]; then
        case "$1" in
            -V|--vers*)
                version
                exit 0
                ;;
            -H|-h|--help)
                usage
                exit 0
                ;;
        esac
    else
        usage
        exit 1
    fi
fi

action="$1"
shift

case "${action}" in
    restart|stop|start|condrestart|status)
        for s in $@; do /sbin/service "${s}" "${action}"; done
        ;;
    init-start)
        for s in $@; do 
            /sbin/service "${s}" start
            /sbin/chkconfig "${s}" on
        done
        ;;
    init-stop)
        for s in $@; do 
            /sbin/service "${s}" stop
            /sbin/chkconfig "${s}" off
        done
        ;;
    init-on|init-off)
        for s in $@; do /sbin/chkconfig "${s}" "${action#init-}"; done
        ;;
    *)
        usage
        exit 1
        ;;
esac

# EOF - services
