#!/bin/bash
#
# grpfix -  Script to fix group ownerships and permissions by ensuring all
#           files and directories are owned by the given group and are
#           group-writable and that directories have the SGID bit set.
#
# Written by Wil Cooley <wcooley@nakedape.cc>
#
# $Id$
# $HeadURL$
#

prog=$(basename $0)
VERSION='1.0 ($Revision$)'

usage() {
    cat <<EOF
Usage: ${prog} <group> <path>

Changes all files and directories in <path> to be owned by group <group>.
Ensures that all files and directories are group-writable and that directories 
have the SGID bit set.

EOF
}

if [[ $# -ne 2 ]]; then
    usage
    if [[ "$1" = "-h" ]]; then
        exit 0
    else
        exit 1
    fi
fi

group="$1"
targetpath="$2"

if [[ ! -r "$targetpath" ]]; then
    printf 'Error! %s is not readable.\n' "$targetpath"
    exit 1
fi

# Change the group
chgrp -R "$group" "$targetpath"

# Set the group-writable bit
# Note that some applications, like SSH or Sendmail, might not like a
# group-writable home directory.
chmod -R g+w "$targetpath"

# FIXME: It would be nice to not assume GNU find and xargs here, which makes
# handling filnames with spaces easy by using null-terminated lines, but which
# is not at all portable.

# Set the SGID bit on directories
find "$targetpath" -type d -print0 |
    xargs -0 -r chmod g+s

