#!/bin/bash
#
# Quick script to fetch a MAC address from the ARP table
#
# Written by W. Reilly Cooley <wcooley@nakedape.cc>
#

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
	cat <<EOF
Usage: $(basename $0) [-f1|-f2] <hostname>
Description: Fetches a MAC address from the ARP table
Options:
    -f1 - Colon-separated format (default)
    -f2 - No separators
EOF
	exit 1
fi

if [ $# -eq 2 ]; then
    case "$1" in
        -f1)
            format=colon
            shift
            ;;
        -f2)
            format=nosep
            shift
            ;;
        *)
            printf "Unrecognized format: %s\n" $1 >/dev/stderr
            exit 1
            ;;
        esac
else    # $# -eq 1
    format=colon
fi

ping -c 1 $1 >/dev/null 2>&1

mac=$(arp -a $1 | awk "/$1/ { print \$4}")

if [ "${format}" == "nosep" ]; then
    mac=$(echo ${mac}|sed 's/://g')
fi

echo "${mac}"
