#!/bin/bash
#
# Name: svn-review
# Desc: Display interlarded svn log & diff, like 'git log -p'
#
# Written by Wil Cooley <wcooley@pdx.edu>
#

svn log "$@" |awk '/^r[0-9]+/{gsub("r", "", $1); printf "svn log -c%d; svn diff -c%d;\n", $1, $1}'|sh |less
